# Overview {.unnumbered}

:::{.callout-note}
##### Learning Goals

After completing this chapter, learners should be able to:

* Apply popular mapping workflows to create maps with spatial data
* Assess which workflow works best in different situations
* Apply cartographic best practices to a map composition in R
:::

##### Workshop Description

In this workshop, participants will learn how to use several options for composing maps in R.

##### Software & Data

To fully participate in this workshop, learners will need to attend to the following before the workshop:

1. Download and [install R](https://cran.rstudio.com/)
1. Download and [install RStudio](https://posit.co/download/rstudio-desktop/)
1. Download the [workshop data](https://ucdavis.box.com/s/ozobvtvehgmsnfrizwb2darqfsoqmmgq) and, unzip it, and store it in a location they can find such as a folder dedicated to this workshop (we do not recommend leaving it in your Downloads folder). This is the same data we use in the Cartography for Academic Publications Workshop.

##### Prerequisites

For the best experience, we recommend learners have the following skills before taking this workshop:

* an introductory understanding of programming in R (for example, you are familiar with how to load libraries, load common data formats like a CSV, and are comfortable running basic commands). See DataLab's [R Basics Workshop](https://ucdavisdatalab.github.io/workshop_r_basics/) for help.
* an introductory understanding of spatial data (for example, you are familiar with the difference between raster and vector data). See DataLab's [Spatial Data Formats Workshop](https://ucdavisdatalab.github.io/workshop_spatial_data_formats/) for help.
* (recommended) review the concepts (first section) of DataLab's [Cartography for Academic Publications Workshop](https://github.com/MicheleTobias/Workshop-Cartography-Journal-Figures)
